
services:
  postgres:
    image: postgres:16
    container_name: crm_postgres
    restart: always
    environment:
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_pass
      POSTGRES_DB: crm_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  crm-api:
    image: eclipse-temurin:17-jre
    container_name: crm_api
    restart: always
    depends_on:
      - postgres
    working_dir: /app
    volumes:
      - ./build/libs/crmapi-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: ["java", "-jar", "app.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/crm_db
      SPRING_DATASOURCE_USERNAME: crm_user
      SPRING_DATASOURCE_PASSWORD: crm_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8080:8080"

volumes:
  pgdata: